README.md

添加sdk回调的说明例子

---

compile.sh
src/test/java/org/bcos/channel/test/TestOk.java
tools/bin/compile.sh
tools/bin/web3sdk

1. 修改compile.sh脚本，使得sol转换java出错时，程序能及时中止，直至用户修复错误，再次编译才可成功;
2. 修改web3sdk: 将使用方法的输出作为./web3sdk --help or ./web3sdk help or ./web3sdk -h的输出;
3. 修改实例TestOk日志输出内容

修改合约转换java代码脚本compile.sh && 修改web3sdk脚本，减少不必要输出 && 修改示例TestOk

---

compile.sh
src/test/resources/applicationContext.xml
tools/bin/compile.sh
tools/bin/counter_compile.sh

修改applicationContext.xml，加配置说明和必须配置项说明

修改applicationContext.xml，加配置说明和必须配置项说明

---

doc/guomi_support_manual.md
src/test/resources/applicationContext.xml

修复渗透漏洞
修复 安全工单处理 【10020295】【低风险】区块链开源项目存在一些内网IP泄露

Hao xuan40404 patch 1

---

src/test/java/org/bcos/channel/test/TestOk.java

*Notes* 增加TestOk的超时等待时间，并在超时后继续重试

*Notes* 增加TestOk的超时等待时间，并在超时后继续重试

---

src/main/java/org/bcos/web3j/utils/Async.java
src/main/java/org/bcos/web3j/utils/Web3AsyncThreadPoolSize.java

需要增加配置
<bean id="async" class="org.bcos.web3j.utils.Async">
<constructor-arg type="org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor" ref="pool" />
</bean>

Async支持spring线程池

---

compile.sh
src/test/resources/log4j.properties

add the permission to execute gradlew.sh  and add log description

add the permission to execute gradlew.sh  and add log description

---

src/test/resources/log4j.properties

add log description for log4j.properties

add log description for log4j.properties

---

src/test/resources/applicationContext.xml

upgrade to 1.2.4

---

src/test/resources/applicationContext.xml

fix the problem  ca.crt cannot be found

fix the ca.crt cannot be found

---

src/main/java/org/fisco/bcos/web3j/protocol/core/JsonRpc2_0Web3j.java
src/test/java/org/fisco/bcos/channel/test/contract/PerfomanceOk.java
src/test/java/org/fisco/bcos/channel/test/contract/PerfomanceOk2.java
src/test/java/org/fisco/bcos/channel/test/contract/PerfomanceOk3.java
src/test/java/org/fisco/bcos/temp/ABCTokenTest.java
src/test/java/org/fisco/bcos/temp/AuthorityTable.java
src/test/java/org/fisco/bcos/temp/Cns.java
src/test/java/org/fisco/bcos/temp/Contractdetail.java
src/test/java/org/fisco/bcos/temp/DB.java
src/test/java/org/fisco/bcos/temp/DBTest.java
src/test/java/org/fisco/bcos/temp/DemoByte.java
src/test/java/org/fisco/bcos/temp/Game.java
src/test/java/org/fisco/bcos/temp/Miner.java
src/test/java/org/fisco/bcos/temp/Test1.java
src/test/java/org/fisco/bcos/temp/Test2.java
src/test/java/org/fisco/bcos/temp/Test3.java

sdk 2.0.0 term one 

---

src/main/java/org/bcos/channel/client/Service.java
src/main/java/org/bcos/channel/dto/EthereumResponse.java
src/main/java/org/bcos/channel/handler/ChannelConnections.java
src/main/java/org/bcos/channel/handler/ChannelHandler.java
src/main/java/org/bcos/channel/proxy/Server.java
src/main/java/org/bcos/web3j/protocol/channel/ChannelEthereumService.java

1. separate the rpc timeout and the transaction callback timeout;
2. default thread pool

timeout & threadpool

---

src/test/java/org/fisco/bcos/channel/test/contract/PerfomanceCollector.java
src/test/java/org/fisco/bcos/channel/test/contract/PerfomanceTableInsert.java
src/test/java/org/fisco/bcos/channel/test/contract/PerfomanceTableModify.java
src/test/java/org/fisco/bcos/channel/test/contract/PerfomanceTableQuery.java
src/test/java/org/fisco/bcos/channel/test/contract/PerfomanceTableRemove.java
src/test/java/org/fisco/bcos/channel/test/contract/PerfomanceTableTestCallback.java
src/test/java/org/fisco/bcos/channel/test/contract/TableTest.java
src/test/java/org/fisco/bcos/channel/test/contract/TableTestClient.java

add crud stress test code
add del modify query

add crud stress test code

---

src/main/java/org/fisco/bcos/web3j/crypto/RawTransaction.java
src/main/java/org/fisco/bcos/web3j/crypto/TransactionEncoder.java

2、 RawTransaction class supports serialization

1、Change the encode method of the TransactionEncoder class to public

---

src/main/java/org/fisco/bcos/channel/handler/ChannelConnections.java

change framedecoder to max_value

---

src/test/java/org/fisco/bcos/channel/test/contract/TableTestClient.java

set timeout to 5s

---

src/test/java/org/fisco/bcos/channel/test/contract/TableTestClient.java

fix bug for groupid

---

src/test/java/org/fisco/bcos/channel/test/contract/TableTestClient.java

update web3sdk error code

---

src/main/java/org/fisco/bcos/web3j/precompile/common/PrecompiledCommon.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fisco-bcos/web3sdk/303)

modify BCOS_VERSION from private to public

---

src/main/java/org/fisco/bcos/web3j/abi/datatypes/NumericType.java
src/main/java/org/fisco/bcos/web3j/protocol/core/methods/response/AbiDefinition.java
src/main/java/org/fisco/bcos/web3j/tx/txdecode/ContractAbiUtil.java
src/main/java/org/fisco/bcos/web3j/tx/txdecode/ContractTypeUtil.java
src/main/java/org/fisco/bcos/web3j/tx/txdecode/EventEntity.java
src/main/java/org/fisco/bcos/web3j/tx/txdecode/InputEntity.java
src/main/java/org/fisco/bcos/web3j/tx/txdecode/OutputEntity.java
src/main/java/org/fisco/bcos/web3j/tx/txdecode/RetCode.java
src/main/java/org/fisco/bcos/web3j/tx/txdecode/TransactionDecoder.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fisco-bcos/web3sdk/304)

update decode input

---

src/main/java/org/fisco/bcos/channel/handler/ChannelHandler.java
src/main/java/org/fisco/bcos/channel/proxy/ConnectionPair.java
src/main/java/org/fisco/bcos/web3j/tx/ExtendedRawTransactionManager.java
src/test/java/org/fisco/bcos/channel/test/parallel/parallelok/PerformanceDTCollector.java
src/test/java/org/fisco/bcos/channel/test/parallel/parallelok/PerformanceDTTest.java
src/test/java/org/fisco/bcos/channel/test/parallel/precompile/PerformanceDTCollector.java
src/test/java/org/fisco/bcos/channel/test/parallel/precompile/PerformanceDTTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fisco-bcos/web3sdk/305)

make receipt error more friendly and format code

---

src/main/java/org/fisco/bcos/channel/handler/ChannelHandler.java
src/main/java/org/fisco/bcos/channel/proxy/ConnectionPair.java
src/main/java/org/fisco/bcos/web3j/precompile/common/PrecompiledCommon.java
src/main/java/org/fisco/bcos/web3j/tx/ExtendedRawTransactionManager.java
src/test/java/org/fisco/bcos/channel/test/parallel/parallelok/PerformanceDTCollector.java
src/test/java/org/fisco/bcos/channel/test/parallel/parallelok/PerformanceDTTest.java
src/test/java/org/fisco/bcos/channel/test/parallel/precompile/PerformanceDTCollector.java
src/test/java/org/fisco/bcos/channel/test/parallel/precompile/PerformanceDTTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fisco-bcos/web3sdk/310)

Release 2.0.0 rc3

---

src/main/java/org/fisco/bcos/web3j/tx/txdecode/ContractAbiUtil.java
src/main/java/org/fisco/bcos/web3j/tx/txdecode/ResultEntity.java
src/main/java/org/fisco/bcos/web3j/tx/txdecode/TransactionDecoder.java
src/test/java/org/fisco/bcos/web3j/tx/txdecode/ResultEntityTest.java
src/test/java/org/fisco/bcos/web3j/tx/txdecode/TestTxDecode.java
src/test/java/org/fisco/bcos/web3j/tx/txdecode/TransactionDecoderTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fisco-bcos/web3sdk/314)

reconstruct code for decode tx

---

.classpath
.gitignore
src/integration-test/resources/applicationContext-sample.xml
src/main/java/org/fisco/bcos/channel/client/AmopException.java
src/main/java/org/fisco/bcos/channel/client/Service.java
src/main/java/org/fisco/bcos/channel/dto/ChannelPush.java
src/main/java/org/fisco/bcos/channel/dto/ChannelRequest.java
src/main/java/org/fisco/bcos/channel/dto/ChannelResponse.java
src/test/java/org/fisco/bcos/channel/test/amop/Channel2Client.java
src/test/java/org/fisco/bcos/channel/test/amop/Channel2ClientBin.java
src/test/java/org/fisco/bcos/channel/test/amop/Channel2Server.java
src/test/java/org/fisco/bcos/channel/test/amop/PushCallback.java
src/test/resources/applicationContext-keystore-sample.xml
src/test/resources/applicationContext-sample.xml

amop support binary
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fisco-bcos/web3sdk/308)

amop support binary

---

.travis.yml
build.gradle

ref https://help.aliyun.com/document_detail/123431.html?spm=5176.10695662.1996646101.searchclickresult.721490b3gBd4j3&from=groupmessage&isappinstalled=0

update fastjson version.

---

src/main/java/org/fisco/bcos/channel/client/Service.java
src/main/java/org/fisco/bcos/web3j/protocol/channel/ChannelEthereumService.java
src/main/java/org/fisco/bcos/web3j/utils/Async.java
src/test/java/org/fisco/bcos/channel/test/contract/PerformanceOkDSync.java

Async can initialize the thread pool by constructor

update Async module

---

README.md
doc/README_CN.md

1. update the links of README.md to from zh_CN to en
2. move `Quick Start` after `Documentation` in consideration that it focus on `spring boot starter`
3. update `Join Our Community` to in consistent with `FISCO-BCOS` repo.
please refer to: https://github.com/cyjseagull/web3sdk/tree/master-2.0-latest

update README for web3sdk

---

src/integration-test/resources/applicationContext-sample.xml

add config for topic verify

---

src/test/resources/applicationContext-sample.xml

update config file

---

src/main/java/org/fisco/bcos/channel/client/Service.java
src/main/java/org/fisco/bcos/channel/handler/ChannelHandlerContextHelper.java
src/test/java/org/fisco/bcos/channel/test/amop/Channel2ClientBinNeedVerify.java
src/test/java/org/fisco/bcos/channel/test/amop/Channel2ClientMultiBinNeedVerify.java
src/test/java/org/fisco/bcos/channel/test/amop/Channel2ClientMultiNeedVerify.java
src/test/resources/applicationContext-sample.xml

add multibroadcast and binary send test function

add multibroadcast and binary send test function

---

src/main/java/org/fisco/bcos/channel/client/Service.java
src/main/java/org/fisco/bcos/channel/protocol/ChannelMessageError.java
src/main/java/org/fisco/bcos/web3j/protocol/channel/ChannelEthereumService.java
src/main/java/org/fisco/bcos/web3j/protocol/core/methods/response/TransactionReceipt.java
src/test/java/org/fisco/bcos/channel/test/parallel/parallelok/PerformanceDTCollector.java

add receipt error callback

---

.ci/ci_check.sh
src/main/java/org/fisco/bcos/channel/dto/BcosBlockNotification.java
src/main/java/org/fisco/bcos/channel/dto/BcosHeartbeat.java
src/main/java/org/fisco/bcos/channel/protocol/ChannelHandshake.java
src/main/java/org/fisco/bcos/channel/protocol/ChannelProtocol.java

https://github.com/FISCO-BCOS/FISCO-BCOS/pull/995

rename channel v2 protol key words

---

src/main/java/org/fisco/bcos/channel/client/Service.java
src/main/java/org/fisco/bcos/channel/handler/ChannelConnections.java
src/main/java/org/fisco/bcos/channel/proxy/Server.java

Release 2.1.0 fix proxy

---

src/main/java/org/fisco/bcos/web3j/codegen/SolidityFunctionWrapper.java

support long binary and abi

---

src/main/java/org/fisco/bcos/channel/handler/ChannelConnections.java

Fix the problem that web3sdk can't parse IPv6 address

Adapt to IPv6

---

src/main/java/org/fisco/bcos/channel/handler/ChannelConnections.java

Fix the problem that web3sdk cannot connect to IPv6 node probabilistically

Fix connection problem for ipv6 peer
